package tools

import (
	"bytes"
	"encoding/json"
	"sort"
	"strings"
)

// RenderToolsMarkdown renders a single markdown document for a set of tool specs.
func RenderToolsMarkdown(specs []ToolSpec) string {
	// stable order
	sorted := append([]ToolSpec{}, specs...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Tether tool reference\n\n")
	b.WriteString("_Generated by:_ `go run ./cmd/tether-tooldocs`\n\n")
	b.WriteString("This document describes the tools available to the Tether agent.\n")
	b.WriteString("Tools are invoked via OpenAI/OpenRouter-style function calling: the model sends JSON arguments matching the tool’s **input schema**, the tool returns JSON matching the documented **output shape**.\n\n")
	b.WriteString("Notes:\n\n")
	b.WriteString("- **InputSchema** is enforced indirectly (the model is guided by the schema); the server still validates critical fields at runtime.\n")
	b.WriteString("- **OutputSchema** is documentation only (tool calling protocols don’t support output schemas yet).\n")
	b.WriteString("- Tools may truncate outputs to protect context size.\n\n")

	b.WriteString("## Index\n\n")
	for _, s := range sorted {
		b.WriteString("- [`" + s.Name + "`](#" + anchor(s.Name) + ") — " + s.Summary + "\n")
	}
	b.WriteString("\n")

	for _, s := range sorted {
		b.WriteString(RenderToolMarkdown(s))
		b.WriteString("\n")
	}

	return strings.TrimSpace(b.String()) + "\n"
}

func RenderToolMarkdown(s ToolSpec) string {
	var b strings.Builder
	b.WriteString("## `" + s.Name + "`\n\n")
	if strings.TrimSpace(s.Category) != "" {
		b.WriteString("_Category:_ `" + s.Category + "`\n\n")
	}
	b.WriteString(strings.TrimSpace(s.Summary) + "\n\n")

	if strings.TrimSpace(s.Safety) != "" {
		b.WriteString("**Safety / confirmation**\n\n")
		b.WriteString(strings.TrimSpace(s.Safety) + "\n\n")
	}

	b.WriteString("### Input schema\n\n")
	b.WriteString("```json\n" + prettyJSON(s.InputSchema) + "\n```\n\n")

	if s.OutputSchema != nil {
		b.WriteString("### Output shape\n\n")
		b.WriteString("```json\n" + prettyJSON(s.OutputSchema) + "\n```\n\n")
	}

	if len(s.Examples) > 0 {
		b.WriteString("### Example\n\n")
		ex := s.Examples[0]
		if strings.TrimSpace(ex.Title) != "" {
			b.WriteString("**" + strings.TrimSpace(ex.Title) + "**\n\n")
		}
		b.WriteString("Tool arguments:\n\n")
		b.WriteString("```json\n" + prettyJSON(ex.Args) + "\n```\n\n")
		if ex.Result != nil {
			b.WriteString("Example result:\n\n")
			b.WriteString("```json\n" + prettyJSON(ex.Result) + "\n```\n\n")
		}
		if strings.TrimSpace(ex.Notes) != "" {
			b.WriteString("Notes: " + strings.TrimSpace(ex.Notes) + "\n\n")
		}
	}

	return b.String()
}

func prettyJSON(v any) string {
	if v == nil {
		return "null"
	}
	buf := &bytes.Buffer{}
	enc := json.NewEncoder(buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	_ = enc.Encode(v)
	return strings.TrimRight(buf.String(), "\n")
}

func anchor(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "")
	s = strings.ReplaceAll(s, ".", "")
	s = strings.ReplaceAll(s, "_", "-")
	s = strings.ReplaceAll(s, "`", "")
	return s
}
